language: python
python:
- '3.8'
- '3.9'
install:
- pip3 install ".[testing]"
script:
- mypy hier_config
- pylint --rcfile=pylintrc hier_config
- pytest
after_success:
- cd docs/_mkdocs; ./mkdocs.sh; cd -
deploy:
- provider: pages
  github-token: "$GITHUBTOKEN"
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  local-dir: docs
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.8"
- provider: pypi
  user: __token__
  password:
    secure: p3pDjjtkYkArelx7DECSMBKZ66N18g6VtTSMkZEUitZyviBBUcHKf4OO2fBRbhovICAbVTdLXrInyKCDACLafPXId8EppbMLzc0T8EKxg7af/xaAwvaBs1shrPoWTKUXxodudrv2lloC2FkZcOMtPa628O27aBks905w/1j6GB8FPN9nIR6KrC7Bxp4TKoPEhVFbp4eSgIwfLmsHRhDkk0Z9qxeaaq0AY5BL/kohYcvJuxeOxSjJ6MP6jN/euPYvVRaKFmIsua7SynLpCWFa9Fjj2tAGENWac1b+tJ/1hQvc600vNMZQwB067MfOOF1NAAj5BfXboZUnhZsztbfAhskw/hoEG6lX48ea4fz7sc2RWamPEYgT1pZl0euRDZuVWflo2tYqMEhqZOeCNA+q2kaYpD7dFBqG7NBhQz/udqLVvfD0rRQgcHaJNFIaD7yh5UlereGZbjG0630vPzQrUPmzFZ+YGrQb8H5Pc/eTNbo4Ho6dKWGBbvXYZwSq5zE80wotNiPvUVUozml0LiWaU7b7CuOBZrqNVdRCjE2JGlaX2U1Gl6mUwCAySEgVscvG4bqa3Z5YW24eSVc7pKcnWGSc/yDJUE2/Xaq7o6oHCm0OedDoPuJIqzvHixYU3679bRMtc4oeR7oES6ApFmMf5xRKyncIePo5+WBeN0rTIm0=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.8"
