---
language: python

python:
- "3.6"

install:
- "python setup.py install"

script:
- "python ./tests/tests.py"

after_success:
- "cd docs/_mkdocs; ./mkdocs.sh; cd -"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUBTOKEN
  keep-history: true
  on:
    branch: master
