name: deploy to github pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# on:
#   release:
#    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine sphinx sphinx_rtd_theme
    - name: Build docs
      run: |
        git checkout -b gh-pages
        cd docs/_mkdocs
        sphinx-apidoc -f -o hier_config ../../hier_config
        make github
        cd -
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.HIER_TOKEN }}
        publish_dir: ./docs
